spring:
  application:
    name: Service-04-Cloud-Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Eshwar-B/Configuration-Properties.git

server:
  port: 9093
