spring:
  application:
    name: Service-03-API-Gateway
  cloud:
    gateway:
      routes:
        - id: api-1
          uri: lb://Service-01-welcome
          predicates:
            - Path=/welcome
        - id: api-2
          uri: lb://Service-02-greet
          predicates:
            - Path=/greet

server:
  port: 3333
